# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'


target 'MessengerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'QuickBlox'
   pod 'Quickblox-WebRTC'

  # Pods for MessengerDemo

end
